analysis:
  n_cores: 1
  preload_attempts: 250
fits:
  flip_for_ds9: true
grid:
  remove_projected_centre: false
hpc:
  hpc_mode: false
  iterations_per_update: 5000
hyper:
  hyper_minimum_percent: 0.01
  hyper_noise_limit: 100000000.0
  stochastic_outputs: false
inversion:
  check_solution_default: false        # When an Inversion checks solutions in case they are numerically unstable by default or not (e.g. InversionSettings.check_solution).
model:
  ignore_prior_limits: true
numba:
  cache: true
  nopython: true
  parallel: false
  use_numba: true
output:
  force_pickle_overwrite: false
  info_whitespace_length: 80
  log_file: output.log
  log_level: INFO
  log_to_file: false
  model_results_decimal_places: 3
  remove_files: false
  samples_to_csv: false
pixelization:
  voronoi_nn_max_interpolation_neighbors: 100
structures:
  use_dataset_grids: true
test:
  check_figure_of_merit_sanity: false
  bypass_figure_of_merit_sanity: false
  check_preloads: false
